my_string = input()
print(f"Number of characters: {len(my_string)}")
print(f"UPPER: {my_string.upper()}")
print(f"lower: {my_string.lower()}")
my_string = my_string.replace(' ', '')
print(my_string[0])
print(my_string[-1])
